### ISSUE TITLE
[Bug?] Containers can be dragged into themselves

### ISSUE THREAD

**Issue by megahead11** [xaukael/griddy#6]
I found a bug that can be weird to un-stuck. It turns out you can drag backpacks into themselves. I don't mean stacking backpacks - I mean, you can open a backpack, and then drag it from the main inventory grid into itself. Once you close the backpack, it is forever nested into itself and cannot be retrieved?  You can fix this by dragging the backpack back into the grid but uh... I don't think this should be intentional.

Kind of a funny recursive bug but I imagine this is probably gonna cause weird breakages...

https://github.com/xaukael/griddy/assets/21242682/2d4b4ba0-7bcc-4329-a1a6-b4027d154259

**Comment by xaukael** [comment]
That is funny because I had an issue earlier where I dropped my backpack on itself and I had to go fix the position.n flag manually to get it back. I fixed that, but did not even consider that someone would drag their backpack into their backpack's window. I am in the middle of a bit of a rewrite to add some enhancements, but I should have a fix to prevent this from happening released sometime today.

**Comment by xaukael** [comment]
Fixed in 1.0.16
