### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Orionox** [xaukael/griddy#8]
Alright so first of, this is amazing and literally one of the best inventory modules I've ever seen. Thank you for making this and I hope you continue to update and improve it. 

Now that, that is out of the way. Here are a few suggestions or requests. 

1. Highlight Items in the character sheet inventory that are overlapping in the grid view. Or send a message every time a character sheet is opened that items in the inventory are overlapping. 
2. Message that plays when someone adds something to a "full inventory"
3. I know this is a moonshot and likely not to happen, but full-blown integration with tidy5e sheet where it actually replaces the default inventory space would be phenomenal.
4. Auto-exclude items that are equipped. 
5. Similiar to backpack manager, the ability to set an item as a way to oen the grid instead of the grid icon. Then have individual items able to be opened directly to their grid.

**Comment by xaukael** [comment]
1. system/sheet specific and overlapping is often a fluctuating thing
2. I can sort of imagine the intent here, but a data driven definition of full is tricky
3. hypothetically possible, though very tricky and system/module spicific
4. system specific and part of my dnd5e world script example that I may make a module further down the line, but is extremely preferential 
5. system/sheet specific, could be implemented in a world script

All of these are things I considered. Most were dropped in an effort to keep it system agnostic. Some where dropped because the functions desired behavior is a matter of opinion and implementing it into the module would result in more and more change requests as others with differing opinions about how it should work started using it. 

It may sound like a cop-out, but making something good is mostly about limiting its scope. If you try to add too much, it becomes too niche, buggy, and unmanageable.

Some of this could be done in a world script. Some of it has already been done, and by me, but it will not be making it into this module.
