### ISSUE TITLE
Possible to check if container is full with API?

### ISSUE THREAD

**Issue by MastaGooz** [xaukael/griddy#9]
Hi,

Loving this module so far !!!

I've had some "possible improvements" ideas : 
- is there a way to check if a container si "full" (when item overlap with the red border), maybe with the API? So it would be possible to set an alert or something.
- when i drop an "container" item from my inventory, all objects contained in this container are deleted (maybe prevent container to be dropable if they are not empty, or find a way to keep the stuff inside?), i'm talking about droping it with Item Pile for example.

Keep up the good work !

**Comment by xaukael** [comment]
Overlaps are detected and the red outline is applied when the a grid is rendered. It would technically be possible to do so logically without rendering it. Others have suggested something similar, like messages to the GM when an inventory is too full, but the auto resolving when you move or rotate items over others depends on forcing that state. Which is my way of saying that which items are overlapping can fluctuate frequently. What would be the in-game purpose of such a function? 

I will add in the next version some logic on container item deletion to have it dump all the items that were in it into the actor's inventory.

**Comment by MastaGooz** [comment]
The purpose is just to prevent players from getting more items than they should (based on the slots of griddy).

**Comment by xaukael** [comment]
Adding logic to this to prevent adding items is not going to happen. It would add way too many points of potential failure of expected behavior. It is easy enough to calculate the available free spaces in the grid or a containers, but whether something will fit is another more complicated question. To add to that, changing the dimensions of an item may also result in the amount of free spaces changing, so I cannot only do such a check before an item is created.

It is always good to remember when working within foundry that it is a virtual table top and not a video game. The most important part being that there is a game master present to arbitrate what can happen. I expect imposing strict handling of items fitting or not in the grid would not only be complex and buggy, but would not even be always desired. 

My proposed solution would be a manual check that that GM can do, with a macro like below. If you have tweaks you would like to make to it, contact me on discord.
```
let content = ``
for (let a of game.actors.filter(a=>a.getFlag('griddy','config'))) {
  let items = a.items.filter(i=>
  game.settings.get('griddy', 'itemTypes').includes(i.type) &&
  !i.flags.griddy?.position?.e
  )
  let notInContainer = items.filter(i=>!i.flags.griddy?.position?.n)

  content += `${a.name}&emsp;
  ${notInContainer.reduce((a,i)=>a+=i.getFlag('griddy', 'position.w')*i.getFlag('griddy', 'position.h'),0)} / ${ character.getFlag('griddy', 'config.cols')*character.getFlag('griddy', 'config.rows')}<br>`

  for (let c of items.filter(i=>i.flags.griddy?.position?.c)) {
    content += `&emsp;${c.name}&emsp;
    ${c.getFlag('griddy', 'position.cols')*c.getFlag('griddy', 'position.rows')} / ${items.filter(i=>i.getFlag('griddy', 'position.n')==c.id).reduce((a,i)=>a+=i.getFlag('griddy', 'position.w')*i.getFlag('griddy', 'position.h'),0)}<br>`
  }
}
Dialog.prompt({content})
```
![image](https://github.com/xaukael/griddy/assets/37848032/8d14c5bc-2177-4e46-b796-a4be73be8f5d)

**Comment by MastaGooz** [comment]
That's perfect ! All I needed was a quick GM check. Thank's a lot !
